/-
Copyright (c) 2026 Yan Senez. All rights reserved.
Released under Apache 2.0 license.
-/
import Mathlib.RingTheory.UniqueFactorizationDomain.Nat
import Mathlib.Data.Nat.Prime.Basic
import Mathlib.Tactic

/-!
# N3a — Minimal Monoid: `(ℕ, ×)` is the canonical UFD substrate of PT

**Statement (paper-level, Ch02 §"Minimal monoid").**
The multiplicative monoid `(ℕ, ×)` is the **minimal** monoid carrying the
PT sieve, in the sense that:

* it is a **unique factorisation monoid** (every nonzero `n` factors
  uniquely, up to units, into primes / irreducibles);
* it is **commutative**;
* it is **cancellative on nonzero elements** (no nontrivial divisors of zero
  in the multiplicative theory of `ℕ \ {0}`);
* its **atoms are exactly the primes** (`Nat.Prime`).

Any monoid carrying the PT axioms (sieve, cascade, cyclic-phase identity) must
contain a sub-structure isomorphic to `(ℕ \ {0}, ×)`, because:

1. the cascade is generated by `{2, 3, 5, 7, …}` (the primes — its atoms);
2. the multiplicative law on those generators yields all of `ℕ \ {0}` by
   uniqueness;
3. the associative + commutative structure is forced by sieve transitivity
   (T1 forbidden transitions, cf. `PT.Sieve.T1ForbiddenTransitions`).

This file formalises the *positive* direction of N3a: `(ℕ, ×)` actually has
all the required structural properties. The minimality direction (no smaller
monoid suffices) is a meta-theorem, recorded as a docstring claim because
Lean cannot quantify over arbitrary monoid carriers without category-theoretic
overhead beyond the scope of this file.

## Mathlib lemmas used

* `Nat.instUniqueFactorizationMonoid` — the UFM instance on `ℕ`
  (`Mathlib.RingTheory.UniqueFactorizationDomain.Nat`).
* `Nat.irreducible_iff_prime` — atoms of `ℕ` (in `Mathlib`'s sense:
  `Irreducible`) coincide with `Nat.Prime`.
* `CommMonoidWithZero.instCommMonoidWithZero` on `ℕ` — commutativity.
* `CancelMonoidWithZero` on `ℕ` — cancellation on nonzero elements.

## Reference

Monograph Chapter 2, §"Monoid minimality", `\label{thm:N3a}`.
Audit row #3 (MEDIUM, ~3 sessions): "Mathlib group theory + UFD structure."

## Strategy

Each structural property is established by either `inferInstance` (the
Mathlib instance is exposed) or a one-line proof. The atoms-are-primes
correspondence uses `Nat.irreducible_iff_prime`.
-/

namespace PT.Sieve

/-! ### Structural instances of `(ℕ, ×)` -/

/-- `ℕ` is a commutative monoid with zero (multiplicative). -/
example : CommMonoidWithZero ℕ := inferInstance

/-- `ℕ` satisfies multiplication cancellation on the nonzero side (modern
    Mathlib spelling: `IsCancelMulZero`). -/
example : IsCancelMulZero ℕ := inferInstance

/-- `ℕ` carries unique factorisation (Mathlib instance). -/
example : UniqueFactorizationMonoid ℕ := inferInstance

/-! ### Atoms of `(ℕ, ×)` are exactly the primes

In Mathlib, the "atoms" of a `Monoid` come in two flavours:
`Irreducible n` (the order-theoretic notion: nontrivial, not a product of two
non-units) and `Prime n` (the divisibility notion). For `ℕ`, these coincide
with `Nat.Prime n`. -/

/-- **Atoms = primes (Nat.Prime ↔ Irreducible).** A natural number is an atom
    of `(ℕ, ×)` (in Mathlib's `Irreducible` sense) iff it is a prime number.
    The Mathlib reduction `Nat.irreducible_iff_prime` does the work. -/
theorem nat_atoms_are_primes (n : ℕ) :
    Nat.Prime n ↔ Irreducible n := by
  rw [Nat.irreducible_iff_prime, ← Nat.prime_iff]

/-- **Atoms = primes (Nat.Prime ↔ Prime).** The divisibility-flavour atom
    coincides with `Nat.Prime`. -/
theorem nat_atoms_are_prime_div (n : ℕ) :
    Nat.Prime n ↔ _root_.Prime n :=
  Nat.prime_iff

/-! ### Existence and uniqueness of prime factorisation -/

/-- **Existence (any nonzero `n`).** Every nonzero natural number factors as a
    product of primes (i.e. `Nat.Prime`).

    Mathlib lemma: `Nat.prod_primeFactorsList`. -/
theorem nat_exists_prime_factorisation (n : ℕ) (hn : n ≠ 0) :
    (n.primeFactorsList.prod = n)
      ∧ (∀ p ∈ n.primeFactorsList, Nat.Prime p) := by
  refine ⟨Nat.prod_primeFactorsList hn, ?_⟩
  intro p hp
  exact Nat.prime_of_mem_primeFactorsList hp

/-- **Uniqueness (atom-multiplicity form).** Two multisets of primes whose
    products are associated (= equal in `ℕ`, since `ℕ` has no nontrivial
    units) are themselves equal as multisets. This is the strict UFM uniqueness
    statement on `ℕ`. -/
theorem nat_unique_prime_factorisation
    (s₁ s₂ : Multiset ℕ)
    (h₁ : ∀ x ∈ s₁, Nat.Prime x) (h₂ : ∀ x ∈ s₂, Nat.Prime x)
    (heq : s₁.prod = s₂.prod) :
    s₁ = s₂ := by
  -- Convert Nat.Prime into Irreducible via `nat_atoms_are_primes`.
  have h₁' : ∀ x ∈ s₁, Irreducible x :=
    fun x hx => (nat_atoms_are_primes x).mp (h₁ x hx)
  have h₂' : ∀ x ∈ s₂, Irreducible x :=
    fun x hx => (nat_atoms_are_primes x).mp (h₂ x hx)
  -- Mathlib uniqueness gives associated multisets, then `associated_iff_eq` on ℕ.
  have hprod_assoc : Associated s₁.prod s₂.prod := heq ▸ Associated.refl _
  have hassoc : Multiset.Rel Associated s₁ s₂ :=
    UniqueFactorizationMonoid.factors_unique h₁' h₂' hprod_assoc
  -- Replace `Associated` by `(· = ·)` on ℕ via `associated_eq_eq`
  -- (`ℕˣ` is a singleton), then collapse `Multiset.Rel Eq` to multiset
  -- equality via `Multiset.rel_eq`.
  rw [associated_eq_eq] at hassoc
  rwa [Multiset.rel_eq] at hassoc

/-! ### Monoidal axioms re-stated for emphasis -/

/-- Commutativity of `(ℕ, ×)`. -/
theorem nat_mul_comm (a b : ℕ) : a * b = b * a := Nat.mul_comm a b

/-- Associativity of `(ℕ, ×)`. -/
theorem nat_mul_assoc (a b c : ℕ) : (a * b) * c = a * (b * c) := Nat.mul_assoc a b c

/-- `1` is the multiplicative identity. -/
theorem nat_one_mul (a : ℕ) : 1 * a = a := Nat.one_mul a

/-- Cancellation on nonzero left factors. -/
theorem nat_mul_left_cancel {a b c : ℕ} (ha : a ≠ 0) (h : a * b = a * c) : b = c :=
  Nat.eq_of_mul_eq_mul_left (Nat.pos_of_ne_zero ha) h

/-! ### N3a, headline form -/

/-- **N3a — `(ℕ, ×)` is the canonical UFM substrate of PT.** Aggregated
    statement: `ℕ` is a commutative cancellative monoid with zero, carrying
    unique factorisation, whose atoms are exactly the primes.

    This is the "minimal monoid" claim in its *positive* form (existence of
    the required structure). The full minimality (no smaller carrier suffices
    for the PT sieve) is a meta-statement at the level of category-theoretic
    free generation; see monograph Ch02 §"Monoid minimality" for the
    informal proof. -/
theorem N3a_nat_is_canonical_UFM :
    (∀ a b : ℕ, a * b = b * a)                        -- commutative
    ∧ (∀ {a b c : ℕ}, a ≠ 0 → a * b = a * c → b = c)  -- cancellative on ≠0
    ∧ (∀ n : ℕ, Nat.Prime n ↔ Irreducible n)          -- atoms = primes
    ∧ (∀ n : ℕ, n ≠ 0 → ∃ s : Multiset ℕ,             -- factor existence
        (∀ x ∈ s, Nat.Prime x) ∧ s.prod = n) := by
  refine ⟨nat_mul_comm, ?cancel, nat_atoms_are_primes, ?factor⟩
  case cancel =>
    intro a b c ha h
    exact nat_mul_left_cancel ha h
  case factor =>
    intro n hn
    refine ⟨n.primeFactorsList, ?_, Nat.prod_primeFactorsList hn⟩
    intro p hp
    exact Nat.prime_of_mem_primeFactorsList hp

end PT.Sieve
