/-
Copyright (c) 2026 Yan Senez. All rights reserved.
Released under Apache 2.0 license.
-/
import PT.Sieve.LegendreLogParity
import PT.Sieve.T1AntidiagOrbits
import PT.Sieve.T1OrbitsZMod5
import PT.Sieve.T1OrbitsZMod7
import Mathlib.Data.ZMod.Basic
import Mathlib.Tactic

/-!
# Primitive root cascade across the PT-active primes `p ∈ {3, 5, 7}`

The Persistence Theory selects three "active" primes `{3, 5, 7}` (cf. T6 and
the dimensional cascade `μ⋆ = 15`). On each of the multiplicative groups
`(ℤ/pℤ)^*` the orbit structure of the corresponding sieve transfer is
generated by a primitive root:

| `p` | `(ℤ/pℤ)^*` | primitive root `g_p` | order `φ(p)` |
|-----|------------|----------------------|--------------|
| `3` | `{1, 2}`         | `g_3 = 2` | `2` |
| `5` | `{1, 2, 3, 4}`   | `g_5 = 2` | `4` |
| `7` | `{1, …, 6}`      | `g_7 = 3` | `6` |

This file collects these three primitive roots in one place and proves:

1. **Primitivity by enumeration.** For each `(p, g_p)`, `(g_p : ZMod p)^k ≠ 1`
   for `1 ≤ k < φ(p)` and `(g_p)^{φ(p)} = 1`.
2. **Dimensional cascade of orders.** `φ(3) = 2 < φ(5) = 4 < φ(7) = 6`.
3. **Generation of `(ℤ/pℤ)^*`.** For each active `p`, the powers
   `{g_p^k : 0 ≤ k < φ(p)}` cover the multiplicative group `(ℤ/pℤ)^*`.
4. **PT "small-root" observation.** The three primitive roots `(2, 2, 3)`
   are themselves bounded by `3 = p_3` (the largest active prime divided
   by `7/3`).
5. **Inactivity comparison.** For `p = 11`, `2` is *not* a primitive root
   modulo `11`: its order divides `10` and is `< 10` (in fact equals `10`,
   so `2` *is* primitive mod `11`, but the role of `2` in the active cascade
   stops at `p = 5`). For `p = 13`, the analogous remark is recorded.

Everything is proved by `decide` on the four-element field `ZMod 5` and its
neighbours, riding on top of `PT.Sieve.LegendreLogParity`,
`PT.Sieve.T1AntidiagOrbits`, `PT.Sieve.T1OrbitsZMod5`, and
`PT.Sieve.T1OrbitsZMod7`.

## Reference

Chapter 7 of the monograph (sieve transfer and active primes), and Theorems
T1/T6 (active-prime selection). Companion to the orbit-structure files
`T1AntidiagOrbits` / `T1OrbitsZMod5` / `T1OrbitsZMod7`.
-/

namespace PT.Sieve

/-! ### The PT primitive-root table -/

/-- The PT-canonical primitive root for an active prime `p ∈ {3, 5, 7}`,
    extended by `0` outside that set. -/
def primitiveRootPT : ℕ → ℕ
  | 3 => 2
  | 5 => 2
  | 7 => 3
  | _ => 0

@[simp] lemma primitiveRootPT_three : primitiveRootPT 3 = 2 := rfl
@[simp] lemma primitiveRootPT_five  : primitiveRootPT 5 = 2 := rfl
@[simp] lemma primitiveRootPT_seven : primitiveRootPT 7 = 3 := rfl

/-- Euler totient on the PT-active primes, extended by `0` outside. -/
def phiPT : ℕ → ℕ
  | 3 => 2
  | 5 => 4
  | 7 => 6
  | _ => 0

@[simp] lemma phiPT_three : phiPT 3 = 2 := rfl
@[simp] lemma phiPT_five  : phiPT 5 = 4 := rfl
@[simp] lemma phiPT_seven : phiPT 7 = 6 := rfl

/-! ### Primitivity for `p = 3`: `g = 2`, `φ(3) = 2` -/

/-- `(2 : ZMod 3)^2 = 1`. -/
theorem two_pow_two_mod3 : (2 : ZMod 3)^2 = 1 := by decide

/-- `(2 : ZMod 3)^1 ≠ 1`. -/
theorem two_pow_one_ne_one_mod3 : (2 : ZMod 3)^1 ≠ 1 := by decide

/-- **`2` is a primitive root mod `3` (minimality).** `(2 : ZMod 3)^1 ≠ 1`
    while `(2 : ZMod 3)^2 = 1`, so the multiplicative order is exactly
    `φ(3) = 2`. -/
theorem two_primitive_root_mod3 :
    (2 : ZMod 3)^1 ≠ 1 ∧ (2 : ZMod 3)^2 = 1 :=
  ⟨two_pow_one_ne_one_mod3, two_pow_two_mod3⟩

/-! ### Primitivity for `p = 5`: `g = 2`, `φ(5) = 4` -/

/-- `(2 : ZMod 5)^1 ≠ 1`. -/
theorem two_pow_one_ne_one_mod5 : (2 : ZMod 5)^1 ≠ 1 := by decide

/-- `(2 : ZMod 5)^2 ≠ 1`. -/
theorem two_pow_two_ne_one_mod5 : (2 : ZMod 5)^2 ≠ 1 := by decide

/-- `(2 : ZMod 5)^3 ≠ 1`. -/
theorem two_pow_three_ne_one_mod5 : (2 : ZMod 5)^3 ≠ 1 := by decide

/-- `(2 : ZMod 5)^4 = 1`. -/
theorem two_pow_four_eq_one_mod5 : (2 : ZMod 5)^4 = 1 := by decide

/-- **`2` is a primitive root mod `5` (minimality).** None of the lower
    powers `(2 : ZMod 5)^k` for `k ∈ {1, 2, 3}` equals `1`, while
    `(2 : ZMod 5)^4 = 1`. The order is exactly `φ(5) = 4`. -/
theorem two_primitive_root_mod5_min :
    (2 : ZMod 5)^1 ≠ 1
    ∧ (2 : ZMod 5)^2 ≠ 1
    ∧ (2 : ZMod 5)^3 ≠ 1
    ∧ (2 : ZMod 5)^4 = 1 :=
  ⟨two_pow_one_ne_one_mod5,
   two_pow_two_ne_one_mod5,
   two_pow_three_ne_one_mod5,
   two_pow_four_eq_one_mod5⟩

/-! ### Primitivity for `p = 7`: `g = 3`, `φ(7) = 6`

These re-export the corresponding lemmas from `T1OrbitsZMod7`. -/

/-- **`3` is a primitive root mod `7` (re-export).** Conjunction form. -/
theorem three_primitive_root_mod7_min :
    (3 : ZMod 7)^1 ≠ 1
    ∧ (3 : ZMod 7)^2 ≠ 1
    ∧ (3 : ZMod 7)^3 ≠ 1
    ∧ (3 : ZMod 7)^4 ≠ 1
    ∧ (3 : ZMod 7)^5 ≠ 1
    ∧ (3 : ZMod 7)^6 = 1 :=
  three_primitive_root_mod7

/-! ### Generation of `(ℤ/pℤ)^*` by the powers of `g_p` -/

/-- **Generation mod 3.** The powers `{2^0, 2^1} = {1, 2}` cover
    `(ℤ/3ℤ)^*`. -/
theorem two_powers_cover_units_mod3 :
    ({((2 : ZMod 3)^0), ((2 : ZMod 3)^1)} : Finset (ZMod 3))
      = ({1, 2} : Finset (ZMod 3)) := by
  decide

/-- **Generation mod 5.** The powers `{2^0, 2^1, 2^2, 2^3}` cover
    `(ℤ/5ℤ)^* = {1, 2, 3, 4}`. -/
theorem two_powers_cover_units_mod5 :
    ({((2 : ZMod 5)^0), ((2 : ZMod 5)^1),
      ((2 : ZMod 5)^2), ((2 : ZMod 5)^3)} : Finset (ZMod 5))
      = ({1, 2, 3, 4} : Finset (ZMod 5)) := by
  decide

/-- **Generation mod 7.** The powers `{3^0, …, 3^5}` cover
    `(ℤ/7ℤ)^* = {1, 2, 3, 4, 5, 6}`. -/
theorem three_powers_cover_units_mod7 :
    ({((3 : ZMod 7)^0), ((3 : ZMod 7)^1), ((3 : ZMod 7)^2),
      ((3 : ZMod 7)^3), ((3 : ZMod 7)^4), ((3 : ZMod 7)^5)}
        : Finset (ZMod 7))
      = ({1, 2, 3, 4, 5, 6} : Finset (ZMod 7)) := by
  decide

/-! ### Dimensional cascade of orders -/

/-- **Dimensional cascade.** `φ(3) = 2 < φ(5) = 4 < φ(7) = 6`. The order of
    the multiplicative group `(ℤ/pℤ)^*` grows strictly across the three
    PT-active primes. -/
theorem phi_cascade_strict :
    phiPT 3 < phiPT 5 ∧ phiPT 5 < phiPT 7 := by
  refine ⟨?_, ?_⟩ <;> decide

/-- **Dimensional cascade (numerical form).** `φ(3) = 2`, `φ(5) = 4`,
    `φ(7) = 6`. -/
theorem phi_cascade_values :
    phiPT 3 = 2 ∧ phiPT 5 = 4 ∧ phiPT 7 = 6 :=
  ⟨rfl, rfl, rfl⟩

/-- **Cascade synchronisation with `T1AntidiagOrbits / T1OrbitsZMod5 /
    T1OrbitsZMod7`.** The orders of the cycle permutations `sigma`,
    `sigma5`, `sigma7` match `φ(3), φ(5), φ(7)`. -/
theorem sigma_orders_match_phi :
    sigma^[phiPT 3]    = (id : Fin 2 → Fin 2)
    ∧ sigma5^[phiPT 5] = (id : Fin 4 → Fin 4)
    ∧ sigma7^[phiPT 7] = (id : Fin 6 → Fin 6) := by
  refine ⟨?_, ?_, ?_⟩
  · -- phiPT 3 = 2
    show sigma^[2] = id
    funext i
    fin_cases i <;> rfl
  · -- phiPT 5 = 4
    exact sigma5_iterate_four
  · -- phiPT 7 = 6
    exact sigma7_iterate_six

/-! ### PT "small-root" observation -/

/-- **PT small-root law (observation).** The three primitive roots
    `(g_3, g_5, g_7) = (2, 2, 3)` are themselves bounded by `3`, i.e. each
    `g_p` is one of the two smallest non-trivial units of `ZMod p`. -/
theorem primitive_roots_small :
    primitiveRootPT 3 ≤ 3
    ∧ primitiveRootPT 5 ≤ 3
    ∧ primitiveRootPT 7 ≤ 3 := by
  refine ⟨?_, ?_, ?_⟩ <;> decide

/-- **PT small-root law, exact list.** `(g_3, g_5, g_7) = (2, 2, 3)`. -/
theorem primitive_roots_tuple :
    primitiveRootPT 3 = 2
    ∧ primitiveRootPT 5 = 2
    ∧ primitiveRootPT 7 = 3 :=
  ⟨rfl, rfl, rfl⟩

/-! ### Inactivity comparison: `p ∈ {11, 13}` -/

/-- For `p = 11`: `(2 : ZMod 11)^k` for `k ∈ {1, …, 9}` is never `1`, while
    `(2 : ZMod 11)^{10} = 1`. So `2` *is* a primitive root mod `11`. The
    point of recording this is that `2` keeps generating the group also at
    `p = 11`, but `11` is *outside* the PT active set; the role of `2` in
    the PT cascade is exhausted at `p = 5`. -/
theorem two_primitive_root_mod11 :
    (2 : ZMod 11)^1 ≠ 1
    ∧ (2 : ZMod 11)^2 ≠ 1
    ∧ (2 : ZMod 11)^3 ≠ 1
    ∧ (2 : ZMod 11)^4 ≠ 1
    ∧ (2 : ZMod 11)^5 ≠ 1
    ∧ (2 : ZMod 11)^6 ≠ 1
    ∧ (2 : ZMod 11)^7 ≠ 1
    ∧ (2 : ZMod 11)^8 ≠ 1
    ∧ (2 : ZMod 11)^9 ≠ 1
    ∧ (2 : ZMod 11)^10 = 1 := by
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩ <;> decide

/-- For `p = 13`: `(2 : ZMod 13)` has order `12` if and only if
    `2^k ≠ 1` for the proper divisors `k ∈ {1, 2, 3, 4, 6}` of `12`.
    Direct check shows `2^{12} = 1` but `2^6 = (12 : ZMod 13) = -1 ≠ 1`.
    However, `2^k` for `k ∈ {2, 3, 4}` also stays `≠ 1`. So `2` *is* a
    primitive root mod `13` as well.

    This isolates the *inactivity* of `p = 11, 13` in the PT cascade: it
    is **not** because `2` fails to generate the multiplicative group, but
    because the active-prime selection rule (T6) excludes them on
    arithmetic grounds (`11, 13 ∤ μ⋆ = 15`). -/
theorem two_primitive_root_mod13 :
    (2 : ZMod 13)^2 ≠ 1
    ∧ (2 : ZMod 13)^3 ≠ 1
    ∧ (2 : ZMod 13)^4 ≠ 1
    ∧ (2 : ZMod 13)^6 ≠ 1
    ∧ (2 : ZMod 13)^12 = 1 := by
  refine ⟨?_, ?_, ?_, ?_, ?_⟩ <;> decide

/-! ### Headline: cascade of primitive roots -/

/-- **Headline.** The PT primitive-root cascade on the active primes
    `{3, 5, 7}`:

    * `(g_3, g_5, g_7) = (2, 2, 3)`, each `≤ 3`.
    * Orders: `φ(3) = 2`, `φ(5) = 4`, `φ(7) = 6`, strictly increasing.
    * Primitivity: in each case the powers `g_p^k` for `k = 1, …, φ(p)-1`
      avoid `1`, and `g_p^{φ(p)} = 1`.
    * Generation: `{g_p^k : 0 ≤ k < φ(p)}` exhausts `(ℤ/pℤ)^*`.
    * Orbit match: the three cycle permutations `sigma`, `sigma5`, `sigma7`
      have orders `φ(3)`, `φ(5)`, `φ(7)` respectively. -/
theorem pt_primitive_root_cascade :
    -- Roots:
    primitiveRootPT 3 = 2
    ∧ primitiveRootPT 5 = 2
    ∧ primitiveRootPT 7 = 3
    -- Strict order cascade:
    ∧ phiPT 3 < phiPT 5 ∧ phiPT 5 < phiPT 7
    -- Primitivity (top exponent equals 1):
    ∧ (2 : ZMod 3)^(phiPT 3) = 1
    ∧ (2 : ZMod 5)^(phiPT 5) = 1
    ∧ (3 : ZMod 7)^(phiPT 7) = 1
    -- Orbit-level matching:
    ∧ sigma^[phiPT 3]    = (id : Fin 2 → Fin 2)
    ∧ sigma5^[phiPT 5] = (id : Fin 4 → Fin 4)
    ∧ sigma7^[phiPT 7] = (id : Fin 6 → Fin 6) := by
  refine ⟨rfl, rfl, rfl, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
  · exact phi_cascade_strict.1
  · exact phi_cascade_strict.2
  · decide
  · decide
  · decide
  · show sigma^[2] = id; funext i; fin_cases i <;> rfl
  · exact sigma5_iterate_four
  · exact sigma7_iterate_six

end PT.Sieve
