/-
Copyright (c) 2026 Yan Senez. All rights reserved.
Released under Apache 2.0 license.
-/
import PT.Stochastic.T3SpectralDecomposition
import PT.Stochastic.T2T3KroneckerEigenvalues
import Mathlib.Tactic

/-!
# Perron / anti commutator — `[Π_+, Π_-] = 0` and `[T_3, Π_±] = 0`

This file investigates the **commutator algebra** generated by `T_3` and
its spectral projectors `Π_+` (Perron, stationary) and `Π_-` (anti,
sign-changing), introduced in `PT.Stochastic.T3SpectralDecomposition`.

The commutator of two matrices is defined as

  `[A, B] := A · B - B · A`.

For the involution `T_3 = !![0, 1; 1, 0]` and its two projectors, the
two-sided orthogonality `Π_+ · Π_- = 0 = Π_- · Π_+` already proved in
`T3SpectralDecomposition.lean` implies that the projectors **commute**:

  `[Π_+, Π_-] = Π_+ · Π_- - Π_- · Π_+ = 0 - 0 = 0`.

Likewise `T_3` itself commutes with each projector: a direct computation
on the explicit `2 × 2` blocks gives

  `T_3 · Π_+ = Π_+`,   `Π_+ · T_3 = Π_+`,
  `T_3 · Π_- = -Π_-`,  `Π_- · T_3 = -Π_-`,

so `[T_3, Π_+] = 0` and `[T_3, Π_-] = 0`. Equivalently the involution
`T_3` acts as the scalar `+1` on the image of `Π_+` (the stationary
sector) and as the scalar `-1` on the image of `Π_-` (the anti sector),
consistent with the spectral decomposition `T_3 = Π_+ - Π_-`.

The algebra `⟨T_3⟩ = {I, T_3}` is the cyclic group `ℤ/2` because
`T_3^2 = I` (involution), so it is **trivially commutative**, and the
spectral resolution `{Π_+, Π_-}` provides the diagonalisation of every
element of this algebra.

We also extend the commutator results to the Kronecker product
`T_2 ⊗ T_3`, where `T_2 = (1)` is the trivial `1 × 1` block (so
`T_2 ⊗ T_3 ≃ T_3` as a `(1 · 2) × (1 · 2)` matrix). Since this is
essentially `T_3` again, all commutation properties pass through.

## Reference

Monograph Chapter 7, §"Algèbre spectrale de `T_3`", continuation of
`T3SpectralDecomposition.lean`. The non-trivial content is the
*statement* `[T_3, Π_±] = 0`, since the explicit projector form and the
involution `T_3 = Π_+ − Π_-` make the commutator into a tautology in the
basis `{Π_+, Π_-}`.
-/

namespace PT.Stochastic

open Matrix Kronecker PT.Sieve

/-! ### Definition of the matrix commutator -/

/-- The **matrix commutator** `[A, B] := A · B − B · A`. -/
def commutator (A B : Matrix (Fin 2) (Fin 2) ℝ) : Matrix (Fin 2) (Fin 2) ℝ :=
  A * B - B * A

/-- The commutator is **antisymmetric**: `[A, B] = -[B, A]`. -/
theorem commutator_antisymm (A B : Matrix (Fin 2) (Fin 2) ℝ) :
    commutator A B = -commutator B A := by
  unfold commutator
  rw [neg_sub]

/-- A matrix commutes with itself: `[A, A] = 0`. -/
theorem commutator_self (A : Matrix (Fin 2) (Fin 2) ℝ) :
    commutator A A = 0 := by
  unfold commutator; simp

/-! ### The Perron / anti projectors commute: `[Π_+, Π_-] = 0` -/

/-- **Commutator nul.** `[Π_+, Π_-] = 0` — the Perron and anti projectors
    commute, because both products `Π_+ · Π_- = 0` and `Π_- · Π_+ = 0`
    vanish (orthogonality), hence so does their difference. -/
theorem commutator_perron_anti_eq_zero :
    commutator perronProjector antiProjector = 0 := by
  unfold commutator
  rw [projectors_orthogonal, projectors_orthogonal']
  simp

/-- **Commutator nul (other order).** `[Π_-, Π_+] = 0`. -/
theorem commutator_anti_perron_eq_zero :
    commutator antiProjector perronProjector = 0 := by
  rw [commutator_antisymm, commutator_perron_anti_eq_zero, neg_zero]

/-! ### `T_3` commutes with each projector: `[T_3, Π_±] = 0` -/

/-- **`T_3 · Π_+ = Π_+`.** The involution `T_3` fixes the Perron sector:
    applied to `Π_+ = (I + T_3)/2` it gives
    `T_3(I + T_3)/2 = (T_3 + T_3²)/2 = (T_3 + I)/2 = Π_+`. -/
theorem T3_mul_perronProjector :
    PT.Sieve.T3 * perronProjector = perronProjector := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [PT.Sieve.T3, perronProjector, stationaryProjector,
          Matrix.mul_apply, Fin.sum_univ_two]

/-- **`Π_+ · T_3 = Π_+`.** The Perron projector absorbs `T_3` on the right
    by the same calculation: `(I + T_3)/2 · T_3 = (T_3 + I)/2 = Π_+`. -/
theorem perronProjector_mul_T3 :
    perronProjector * PT.Sieve.T3 = perronProjector := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [PT.Sieve.T3, perronProjector, stationaryProjector,
          Matrix.mul_apply, Fin.sum_univ_two]

/-- **`T_3 · Π_- = -Π_-`.** The involution `T_3` flips the sign on the
    anti sector: `T_3(I - T_3)/2 = (T_3 - I)/2 = -(I - T_3)/2 = -Π_-`. -/
theorem T3_mul_antiProjector :
    PT.Sieve.T3 * antiProjector = -antiProjector := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [PT.Sieve.T3, antiProjector,
          Matrix.mul_apply, Fin.sum_univ_two] <;>
    norm_num

/-- **`Π_- · T_3 = -Π_-`.** The anti projector flips sign when `T_3` acts
    on the right as well. -/
theorem antiProjector_mul_T3 :
    antiProjector * PT.Sieve.T3 = -antiProjector := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [PT.Sieve.T3, antiProjector,
          Matrix.mul_apply, Fin.sum_univ_two] <;>
    norm_num

/-- **`[T_3, Π_+] = 0`.** The involution `T_3` commutes with the Perron
    projector. Both sides equal `Π_+`. -/
theorem commutator_T3_perronProjector :
    commutator PT.Sieve.T3 perronProjector = 0 := by
  unfold commutator
  rw [T3_mul_perronProjector, perronProjector_mul_T3]
  simp

/-- **`[T_3, Π_-] = 0`.** The involution `T_3` commutes with the anti
    projector. Both sides equal `-Π_-`. -/
theorem commutator_T3_antiProjector :
    commutator PT.Sieve.T3 antiProjector = 0 := by
  unfold commutator
  rw [T3_mul_antiProjector, antiProjector_mul_T3]
  simp

/-! ### Cyclic algebra `⟨T_3⟩ = {I, T_3} ≃ ℤ/2` -/

/-- **`T_3` commutes with the identity** — trivially, `[T_3, I] = 0`. -/
theorem commutator_T3_one :
    commutator PT.Sieve.T3 (1 : Matrix (Fin 2) (Fin 2) ℝ) = 0 := by
  unfold commutator; simp

/-- **`T_3` commutes with `T_3²`** — equivalently, with `I` (since
    `T_3² = I`). Both sides reduce to `T_3 · I = T_3`. -/
theorem commutator_T3_T3sq :
    commutator PT.Sieve.T3 (PT.Sieve.T3 * PT.Sieve.T3) = 0 := by
  rw [T3_sq_eq_one]
  exact commutator_T3_one

/-! ### Extension to `T_2 ⊗ T_3` -/

/-- The Perron projector of `T_2 ⊗ T_3` on the right factor (the only
    non-trivial factor, since `T_2 = (1)` is trivial). We use the
    embedded form `1 ⊗ Π_+`; here, since `T_2 ⊗ T_3` is `(1·2) × (1·2)`,
    this is essentially `perronProjector` reindexed by `Fin 1 × Fin 2`. -/
noncomputable def T2T3_perronProjector :
    Matrix (Fin 1 × Fin 2) (Fin 1 × Fin 2) ℝ :=
  (1 : Matrix (Fin 1) (Fin 1) ℝ) ⊗ₖ perronProjector

/-- The anti projector of `T_2 ⊗ T_3`. Same convention. -/
noncomputable def T2T3_antiProjector :
    Matrix (Fin 1 × Fin 2) (Fin 1 × Fin 2) ℝ :=
  (1 : Matrix (Fin 1) (Fin 1) ℝ) ⊗ₖ antiProjector

/-- The matrix commutator on the `(Fin 1 × Fin 2)`-indexed block. -/
def commutator₂ (A B : Matrix (Fin 1 × Fin 2) (Fin 1 × Fin 2) ℝ) :
    Matrix (Fin 1 × Fin 2) (Fin 1 × Fin 2) ℝ :=
  A * B - B * A

/-- **`[1 ⊗ Π_+, 1 ⊗ Π_-] = 0`.** Since the left factor is `1 × 1` and
    trivial, the Kronecker commutator inherits the orthogonality of the
    right factors. -/
theorem commutator₂_T2T3_perron_anti :
    commutator₂ T2T3_perronProjector T2T3_antiProjector = 0 := by
  unfold commutator₂ T2T3_perronProjector T2T3_antiProjector
  -- Distribute Kronecker over products, then collapse with orthogonality
  rw [← Matrix.mul_kronecker_mul, ← Matrix.mul_kronecker_mul,
      projectors_orthogonal, projectors_orthogonal']
  simp

/-- **`(T_2 ⊗ T_3)` commutes with `(1 ⊗ Π_+)`.** By
    `T_3 · Π_+ = Π_+ · T_3 = Π_+`, both sides equal `1 ⊗ Π_+`. -/
theorem commutator₂_T2T3_perronProjector :
    commutator₂ ((1 : Matrix (Fin 1) (Fin 1) ℝ) ⊗ₖ PT.Sieve.T3)
                T2T3_perronProjector = 0 := by
  unfold commutator₂ T2T3_perronProjector
  rw [← Matrix.mul_kronecker_mul, ← Matrix.mul_kronecker_mul,
      T3_mul_perronProjector, perronProjector_mul_T3]
  simp

/-- **`(T_2 ⊗ T_3)` commutes with `(1 ⊗ Π_-)`.** Both sides equal
    `-(1 ⊗ Π_-)` because `T_3 · Π_- = Π_- · T_3 = -Π_-`. -/
theorem commutator₂_T2T3_antiProjector :
    commutator₂ ((1 : Matrix (Fin 1) (Fin 1) ℝ) ⊗ₖ PT.Sieve.T3)
                T2T3_antiProjector = 0 := by
  unfold commutator₂ T2T3_antiProjector
  rw [← Matrix.mul_kronecker_mul, ← Matrix.mul_kronecker_mul,
      T3_mul_antiProjector, antiProjector_mul_T3]
  simp

/-! ### Headline: the commutator algebra -/

/-- **Headline (commutator algebra).** The pair `(Π_+, Π_-)` together
    with `T_3` and `I` generates a **commutative** matrix algebra:

    * `[Π_+, Π_-] = 0`, `[Π_-, Π_+] = 0`  (projectors commute);
    * `[T_3, Π_+] = 0`, `[T_3, Π_-] = 0`  (`T_3` is diagonal in
      `{Π_+, Π_-}`);
    * `[T_3, I] = 0`                        (trivial);
    * `[T_3, T_3²] = 0`                     (cyclic — `T_3² = I`);
    * `[A, A] = 0` for any `A`              (self-commutator).

    The algebra `⟨T_3⟩ = {I, T_3}` is the cyclic group of order `2`,
    and the spectral resolution `{Π_+, Π_-}` from
    `T3SpectralDecomposition.lean` diagonalises it: every element is a
    real linear combination `α Π_+ + β Π_-` with `α, β ∈ {±1}`, and any
    two such combinations commute. -/
theorem T3_commutator_algebra :
    commutator perronProjector antiProjector = 0
    ∧ commutator antiProjector perronProjector = 0
    ∧ commutator PT.Sieve.T3 perronProjector = 0
    ∧ commutator PT.Sieve.T3 antiProjector = 0
    ∧ commutator PT.Sieve.T3 (1 : Matrix (Fin 2) (Fin 2) ℝ) = 0
    ∧ commutator PT.Sieve.T3 (PT.Sieve.T3 * PT.Sieve.T3) = 0 :=
  ⟨commutator_perron_anti_eq_zero, commutator_anti_perron_eq_zero,
   commutator_T3_perronProjector, commutator_T3_antiProjector,
   commutator_T3_one, commutator_T3_T3sq⟩

end PT.Stochastic
